# Generated by Django 3.2.13 on 2022-06-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_auto_20220601_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperative',
            options={'ordering': ['sigle'], 'verbose_name': 'cooperative', 'verbose_name_plural': 'COOPERATIVES'},
        ),
    ]
