# Generated by Django 3.2.13 on 2022-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_alter_cooperative_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
