# Generated by Django 4.1.3 on 2023-03-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0009_espece_densite_alter_campagne_annee_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espece',
            name='co2_annuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='CO2/AN'),
        ),
    ]
