# Generated by Django 4.0.4 on 2022-05-16 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
#import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0002_alter_activite_id_alter_campagne_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('prix', models.PositiveIntegerField(default=2500)),
                ('arbre', models.PositiveIntegerField(default=0)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name': 'formule',
                'verbose_name_plural': 'FORMULES',
            },
        ),
        migrations.CreateModel(
            name='Souscripteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero_patient', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='NUMERO')),
                ('genre', models.CharField(blank=True, choices=[('H', 'HOMMME'), ('F', 'FEMME')], default='H', max_length=10, null=True, verbose_name='GENRE')),
              #  ('pays', django_countries.fields.CountryField(max_length=2)),
                ('contact', models.CharField(help_text='Veuillez entrer un Numero Au format International Exple: +225 xx xx xx xx xx', max_length=50, verbose_name='TELEPHONE 1')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='ADRESSE')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload_image')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'souscripteur',
                'verbose_name_plural': 'SOUSCRIPTEURS',
                'ordering': ['-add_le'],
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.PositiveIntegerField(blank=True, default=0)),
                ('arbre', models.PositiveIntegerField(blank=True, default=0)),
                ('is_abonne', models.BooleanField(default=False)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formule_souscription', to='marketplace.formule')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.projet')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.region')),
                ('souscripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='marketplace.souscripteur')),
            ],
        ),
    ]
