# Generated by Django 3.2.13 on 2022-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscripteur',
            name='numero_patient',
        ),
        migrations.AddField(
            model_name='souscripteur',
            name='matricule',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='MATRICULE'),
        ),
    ]
