# Generated by Django 3.2.13 on 2022-05-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20220516_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='souscription',
            options={'verbose_name': 'souscription', 'verbose_name_plural': 'SOUSCRIPTIONS'},
        ),
    ]
