# Generated by Django 3.1.7 on 2022-05-03 22:45

import cooperatives.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='parametres.cooperative')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'SECTIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Sous_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.section')),
            ],
            options={
                'verbose_name': 'sous section',
                'verbose_name_plural': 'SOUS SECTIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE PRODUCTEUR')),
                ('type_producteur', models.CharField(choices=[('MEMBRE', 'MEMBRE'), ('USAGER', 'USAGER')], default='MEMBRE', max_length=50, verbose_name='TYPE PRODUCTEUR')),
                ('genre', models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], default='H', max_length=2)),
                ('nom', models.CharField(max_length=250, verbose_name='Nom et prénoms')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date/Année de Naissance')),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_enfant', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('nb_epouse', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('enfant_scolarise', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Enfant Scolarise')),
                ('nb_personne', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Personne à Charge')),
                ('nb_parcelle', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to=cooperatives.models.producteurs_images, verbose_name='Logo')),
                ('type_document', models.CharField(choices=[('AUCUN', 'AUCUN'), ('ATTESTATION', 'ATTESTATION'), ('CNI', 'CNI'), ('PASSEPORT', 'PASSEPORT'), ('SEJOUR', 'CARTE DE SEJOUR'), ('CONSULAIRE', 'CARTE CONSULAIRE')], default='AUCUN', max_length=50, verbose_name='TYPE DOCUMENT')),
                ('num_document', models.CharField(blank=True, max_length=150, null=True, verbose_name='N° PIECE')),
                ('document', models.FileField(blank=True, null=True, upload_to=cooperatives.models.producteurs_documents, verbose_name='Documents')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteurs', to='parametres.cooperative')),
                ('origine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producteurs', to='parametres.origine')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteurs', to='cooperatives.section')),
                ('sous_prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.sous_prefecture')),
                ('sous_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_section', to='cooperatives.sous_section')),
            ],
            options={
                'verbose_name': 'producteur',
                'verbose_name_plural': 'PRODUCTEURS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('code', models.CharField(blank=True, help_text='LE CODE PARCELLE EST GENERE AUTOMATIQUEMENT', max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE PARCELLE')),
                ('code_certificat', models.CharField(blank=True, max_length=150, null=True, unique=b'I01\n', verbose_name='CODE certification')),
                ('annee_certificat', models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='Année certification')),
                ('annee_acquis', models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='Année acquisition')),
                ('acquisition', models.CharField(choices=[('HERITAGE', 'HERITAGE'), ('ACHAT', 'ACHAT'), ('AUTRES', 'AUTRES')], default='heritage', max_length=50, verbose_name='MODE ACQUISITION')),
                ('latitude', models.CharField(blank=True, max_length=12, null=True)),
                ('longitude', models.CharField(blank=True, max_length=12, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('culture', models.CharField(choices=[('ANACARDE', 'ANACARDE'), ('CACAO', 'CACAO'), ('CAFE', 'CAFE'), ('COTON', 'COTON'), ('HEVEA', 'HEVEA'), ('PALMIER', 'PALMIER A HUILE'), ('SOJA', 'SOJA'), ('AUTRE', 'AUTRE')], default='cacao', max_length=50, verbose_name='CULTURE')),
                ('certification', models.CharField(choices=[('UTZ', 'UTZ'), ('RA', 'RA'), ('BIO', 'BIO'), ('PROJET', 'PROJET'), ('AUTRE', 'AUTRE')], default='utz', max_length=50, verbose_name='CERTIFICATION')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='cooperatives.producteur')),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'PARCELLES',
                'ordering': ['-created_at'],
            },
        ),
    ]
