# Generated by Django 3.1.7 on 2022-05-03 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.projet'),
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('code', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE PLANTING')),
                ('nb_plant_exitant', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS EXISTANTS')),
                ('plant_recus', models.PositiveIntegerField(default=0, verbose_name='NOMBRE DE PLANTS RECUS')),
                ('plant_total', models.PositiveIntegerField(default=0, verbose_name='NOMBRE TOTAL DE PLANTS')),
                ('date', models.DateField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='parametres.campagne')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='cooperatives.parcelle')),
            ],
            options={
                'verbose_name': 'planting',
                'verbose_name_plural': 'PLANTINGS',
                'ordering': ['-date'],
                'get_latest_by': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('code', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE ')),
                ('mort_global', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NBRE PLANTS MORTS')),
                ('mature_global', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NBRE PLANTS VIVANTS')),
                ('date', models.DateField()),
                ('taux_vitalite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taux_mortalite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('observation', models.ManyToManyField(blank=True, null=True, related_name='cooperatives_monitoring_observation', to='parametres.ObsMonitoring')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.planting')),
            ],
            options={
                'verbose_name': 'monitoring planting',
                'verbose_name_plural': 'MONITORINGS PLANTINGS',
            },
        ),
        migrations.CreateModel(
            name='DetailPlanting',
            fields=[
                ('code', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE ')),
                ('nb_plante', models.PositiveIntegerField(default=0, verbose_name='QTE recu')),
                ('espece', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.planting')),
            ],
            options={
                'verbose_name': 'details planting',
                'verbose_name_plural': 'DETAILS PLANTINGS',
            },
        ),
    ]
