# Generated by Django 3.1.7 on 2022-05-03 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('cooperatives', '0002_auto_20220503_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMonitoring',
            fields=[
                ('code', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE ')),
            ],
            options={
                'verbose_name': 'details monitoring',
                'verbose_name_plural': 'DETAILS MONITORINGS ',
            },
        ),
        migrations.CreateModel(
            name='DetailPlantingRemplacement',
            fields=[
                ('code', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE ')),
                ('nb_plante', models.PositiveIntegerField(default=0, verbose_name='QTE recu')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.planting')),
            ],
            options={
                'verbose_name': 'details planting remplacement',
                'verbose_name_plural': 'DETAILS PLANTINGS APRES REMPLACEMENT',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formateur', models.CharField(max_length=255, verbose_name='FORMATEUR')),
                ('structureformateur', models.CharField(blank=True, max_length=100, null=True, verbose_name='STRUCTURE FORMATEUR')),
                ('niveauformateur', models.CharField(blank=True, max_length=100, null=True, verbose_name='NIVEAU ETUDE FORMATEUR')),
                ('note_formateur', models.TextField(blank=True, null=True)),
                ('critere', models.CharField(blank=True, choices=[('SATISFAIT', 'SATISFAIT'), ('COMPRIS', 'COMPRIS'), ('NOSATISFAIT', 'PAS SATISFAIT'), ('PASCOMPRIS', 'PAS COMPRIS')], default='', max_length=50, null=True)),
                ('debut', models.DateField(verbose_name='DATE DEBUT')),
                ('fin', models.DateField(verbose_name='DATE FIN')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.campagne')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.cooperative')),
                ('intitule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.intitule_formation')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringEspeceremplacement',
            fields=[
                ('code', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE ')),
                ('recu', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE PLANTS RECU')),
                ('remplacer', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE PLANTS REMPLACER')),
                ('mort', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE PLANTS MORT')),
                ('futur', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='NOMBRE PLANTS PROCHAIN REMPLACEMENT')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
            ],
        ),
        migrations.CreateModel(
            name='Participantcoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=b'I01\n')),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.cooperative')),
            ],
            options={
                'verbose_name': 'participant de la cooperative',
                'verbose_name_plural': 'PARTICIPANTS DE LA COOPERATIVE',
            },
        ),
        migrations.CreateModel(
            name='RemplacementMonitoring',
            fields=[
                ('code', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE ')),
                ('date', models.DateField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('espece', models.ManyToManyField(through='cooperatives.MonitoringEspeceremplacement', to='parametres.Espece')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('code', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE ')),
                ('qteProduct', models.IntegerField(default=0)),
                ('campagne', models.CharField(choices=[('PETITE', 'PETITE CAMPAGNE'), ('GRANDE', 'GRANDE CAMPAGNE')], default='H', max_length=150)),
                # ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.campagne')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.parcelle')),
            ],
            options={
                'verbose_name': 'production/parcelle',
                'verbose_name_plural': 'PRODUCTIONS/PARCELLES',
            },
        ),
        migrations.CreateModel(
            name='Participantformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.formation')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.participantcoop')),
            ],
            options={
                'verbose_name': 'participant de la formation',
                'verbose_name_plural': 'PARTICIPANTS DE LA FORMATION',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='monitoringespeceremplacement',
            name='remplacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.remplacementmonitoring'),
        ),
        migrations.CreateModel(
            name='MonitoringEspece',
            fields=[
                ('code', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE ')),
                ('mort', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MORTS')),
                ('taux_mortalite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detailmonitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.detailmonitoring')),
                ('detailplanting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.detailplanting')),
                ('detailplantingremplacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.detailplantingremplacement')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='participant',
            field=models.ManyToManyField(through='cooperatives.Participantformation', to='cooperatives.Participantcoop'),
        ),
        migrations.AddField(
            model_name='detailplantingremplacement',
            name='remplacer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.remplacementmonitoring'),
        ),
        migrations.AddField(
            model_name='detailmonitoring',
            name='espece',
            field=models.ManyToManyField(through='cooperatives.MonitoringEspece', to='parametres.Espece'),
        ),
        migrations.AddField(
            model_name='detailmonitoring',
            name='monitoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.monitoring'),
        ),
        migrations.CreateModel(
            name='Detail_Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.formation')),
                ('participant', models.ManyToManyField(to='cooperatives.Producteur')),
            ],
            options={
                'verbose_name': 'details formation',
                'verbose_name_plural': 'DETAILS FORMATIONS',
                'ordering': ['formation'],
            },
        ),
    ]
