# Generated by Django 3.1.7 on 2022-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_auto_20220503_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='synchro',
            field=models.CharField(default='NON', max_length=10),
        ),
        migrations.AddField(
            model_name='producteur',
            name='synchro',
            field=models.CharField(default='NON', max_length=10),
        ),
    ]
