# Generated by Django 3.2.13 on 2022-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0005_alter_detail_formation_id_alter_formation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='longitude',
            field=models.CharField(max_length=12),
        ),
    ]
