# Generated by Django 3.2.13 on 2022-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0006_alter_parcelle_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='longitude',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
