# Generated by Django 3.2.13 on 2022-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_auto_20220624_1005'),
        ('cooperatives', '0007_alter_parcelle_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_formation',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='detail_formation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detailmonitoring',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='detailmonitoring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detailplanting',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='detailplanting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detailplantingremplacement',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='detailplantingremplacement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='formation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monitoringespece',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='monitoringespece',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monitoringespeceremplacement',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='monitoringespeceremplacement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participantcoop',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='participantcoop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participantformation',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='participantformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='planting',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='planting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='production',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='production',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='remplacementmonitoring',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AddField(
            model_name='remplacementmonitoring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='observation',
            field=models.ManyToManyField(blank=True, related_name='cooperatives_monitoring_observation', to='parametres.ObsMonitoring'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='longitude',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
        migrations.AlterField(
            model_name='sous_section',
            name='created_at',
            field=models.CharField(default=2022, max_length=150),
        ),
    ]
