# Generated by Django 3.2.13 on 2022-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0008_auto_20220624_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='longitude',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
