# Generated by Django 3.2.13 on 2022-08-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_parcelle_type_parcelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='type_parcelle',
            field=models.CharField(choices=[('AGROFORESTERIE', 'AGROFORESTERIE'), ('COMMUNAUTAIRE', 'COMMUNAUTAIRE'), ('FORET_CLASSEE', 'FORET CLASSEE'), ('PRIVEE', 'PRIVEE'), ('INDIVIDUELLE', 'INDIVIDUELLE')], default='AGROFORESTERIE', max_length=50),
        ),
    ]
