# Generated by Django 3.2.13 on 2022-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0014_alter_parcelle_type_parcelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
