# Generated by Django 3.2.13 on 2022-10-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0015_alter_parcelle_superficie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='synchro',
            field=models.CharField(default='OUI', max_length=10),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='synchro',
            field=models.CharField(default='OUI', max_length=10),
        ),
    ]
