# Generated by Django 3.2.13 on 2022-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0016_auto_20221017_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='type_parcelle',
            field=models.CharField(choices=[('AGROFORESTERIE', 'AGROFORESTERIE'), ('COMMUNAUTAIRE', 'COMMUNAUTAIRE'), ('FORET_CLASSEE', 'FORET CLASSEE'), ('INDIVIDUELLE', 'INDIVIDUELLE'), ('JACHERE', 'JACHERE'), ('MANGROVE', 'MANGROVE'), ('PRIVEE', 'PRIVEE')], default='AGROFORESTERIE', max_length=50),
        ),
    ]
