# Generated by Django 4.1.3 on 2023-02-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0009_espece_densite_alter_campagne_annee_debut_and_more'),
        ('cooperatives', '0018_auto_20221028_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_formation',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='detailmonitoring',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='detailplanting',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='detailplantingremplacement',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='monitoringespece',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='monitoringespeceremplacement',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='annee_acquis',
            field=models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True, verbose_name='Année acquisition'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='annee_certificat',
            field=models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True, verbose_name='Année certification'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='participantcoop',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='participantformation',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='planting',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='production',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='remplacementmonitoring',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.AlterField(
            model_name='sous_section',
            name='created_at',
            field=models.CharField(default=2023, max_length=150),
        ),
        migrations.CreateModel(
            name='ImportProdFileModel',
            fields=[
                ('code', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='CODE PRODUCTEUR')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom et prénoms')),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_parcelle', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(blank=True, choices=[('H', 'HOMME'), ('F', 'FEMME')], default='H', max_length=2, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date/Année de Naissance')),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('nom_prime', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom et prénoms')),
                ('localite_prime', models.CharField(blank=True, max_length=100, null=True)),
                ('section_prime', models.IntegerField(blank=True, null=True)),
                ('nb_parcelle_prime', models.PositiveIntegerField(blank=True, null=True)),
                ('genre_prime', models.CharField(blank=True, max_length=2, null=True)),
                ('dob_prime', models.DateField(blank=True, null=True, verbose_name='Date/Année de Naissance')),
                ('contacts_prime', models.CharField(blank=True, max_length=50, null=True)),
                ('cooperative_prime', models.IntegerField(blank=True, null=True)),
                ('user_id_prime', models.IntegerField(blank=True, null=True)),
                ('etatValidate', models.CharField(blank=True, default='EN ATTENTE', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.cooperative')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.section')),
            ],
        ),
    ]
