# Generated by Django 4.1.3 on 2023-03-27 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0010_espece_co2_annuel'),
        ('cooperatives', '0019_alter_detail_formation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarboneStocke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreAnne', models.IntegerField(default=0)),
                ('carboneStock', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.monitoring')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.parcelle')),
            ],
        ),
    ]
