# Generated by Django 4.1.3 on 2023-05-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0020_carbonestocke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producteur',
            name='enfant_scolarise',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='nb_enfant',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='nb_epouse',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='nb_personne',
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='type_parcelle',
            field=models.CharField(choices=[('AGROFORESTERIE', 'AGROFORESTERIE'), ('REFORESTATION', 'REFORESTATION'), ('COMMUNAUTAIRE', 'COMMUNAUTAIRE'), ('FORET_CLASSEE', 'FORET CLASSEE'), ('INDIVIDUELLE', 'INDIVIDUELLE'), ('JACHERE', 'JACHERE'), ('PRIVEE', 'PRIVEE')], default='AGROFORESTERIE', max_length=50),
        ),
    ]
